import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
export const metadata: Metadata = {
  title: "Give your Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body
          cz-shortcut-listen="true" // Add the attribute
        >
          <ReduxProvider>
            {children}
          </ReduxProvider>

         
        </body>
      </html>
    
  );
}
