import type { Metadata } from "next";
import { Geist, Geist_Mono , Libre_Franklin } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const Libre = Libre_Franklin({
  weight : "200",
  style : "normal"


})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Give your Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body
          // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          cz-shortcut-listen="true" // Add the attribute
        >
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </body>
      </html>
    
  );
}
